--1. listar todo o acervo, com código, título, tipo e disponibilidade.
SELECT CODIGO, TITULO, TIPO, CASE WHEN DISPONIVEL = TRUE THEN 'SIM' ELSE 'NÃO' END AS DISPONIVEL FROM ITEM;

--2. listar os empréstimos em aberto, com o nome do usuário e o título do item.
SELECT U.NOME, U.TIPO, U.LIMITE_ITENS
	 , I.CODIGO AS COD_ITEM, I.TITULO, I.TIPO AS TIPO_ITEM, I.AUTOR, I.EDICAO, I.DISPONIVEL
	 , E.DATA_RETIRADA, E.DATA_DEVOLUCAO_PREVISTA, COALESCE(TO_CHAR(E.DATA_DEVOLUCAO, 'DD/MM/YYYY'), 'Em aberto') AS DATA_DEVOLUCAO_FORMATADA, E.VALOR_MULTA
FROM EMPRESTIMO E
INNER JOIN USUARIO U ON U.ID = E.USUARIO_ID
INNER JOIN ITEM I ON I.ID = E.ITEM_ID
WHERE E.DATA_DEVOLUCAO IS NULL ;

--3. calcular o total de multas acumuladas por usuário.
SELECT U.NOME
     , SUM (E.VALOR_MULTA) AS VALOR_TOTAL_MULTAS
FROM EMPRESTIMO E
INNER JOIN USUARIO U ON U.ID = E.USUARIO_ID
INNER JOIN ITEM I ON I.ID = E.ITEM_ID
WHERE 1=1
GROUP BY U.NOME;

--4. listar os itens que nunca foram emprestados.
SELECT I.CODIGO AS COD_ITEM, I.TITULO, I.TIPO AS TIPO_ITEM, I.AUTOR, I.EDICAO, I.DISPONIVEL
     , E.DATA_RETIRADA, E.DATA_DEVOLUCAO_PREVISTA, COALESCE(TO_CHAR(E.DATA_DEVOLUCAO, 'DD/MM/YYYY'), 'Em aberto') AS DATA_DEVOLUCAO_FORMATADA, E.VALOR_MULTA
FROM ITEM I
LEFT JOIN EMPRESTIMO E ON I.ID = E.ITEM_ID
WHERE E.ID IS NULL ;
